services:
  redisrelay:
    build:
      context: .
      dockerfile: Dockerfile
    read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: redisrelay:latest
    container_name: redisrelay
    restart: on-failure:10
    volumes:
      - ./config.yaml:/config.yaml:ro
    environment:
      - CONFIG_PATH=/config.yaml
      - REDIS_PASSWORD=${REDIS_PASSWORD}
